import fs from "fs/promises";
import path from "path";
import { SCORE_THRESHOLD, scoutDir } from "./config";
import { AuditEntry, HistoryEntry, ScoutRunResult } from "./types";

async function ensureDir() {
  await fs.mkdir(scoutDir(), { recursive: true });
}

export async function persistRun(result: ScoutRunResult) {
  await ensureDir();
  const dir = scoutDir();

  const audit = {
    run_timestamp: result.timestamp,
    candidates_fetched: result.candidatesFetched,
    candidates_read: result.candidatesRead,
    candidates_qualified: result.candidatesQualified,
    new_roles: result.newRoles,
    threshold: result.threshold,
    sources: result.sources,
    entries: result.audit,
  };
  await fs.writeFile(path.join(dir, "audit_log.json"), JSON.stringify(audit, null, 2));

  const capture = result.log.join("\n") + "\n\n--- DIGEST ---\n" + result.digest;
  await fs.writeFile(path.join(dir, "run_capture.txt"), capture);

  const historyEntry: HistoryEntry = {
    date: result.timestamp.slice(0, 10),
    timestamp: result.timestamp,
    candidates_fetched: result.candidatesFetched,
    candidates_read: result.candidatesRead,
    candidates_qualified: result.candidatesQualified,
    digest: result.digest,
    qualified_roles: result.qualified,
  };
  await fs.appendFile(
    path.join(dir, "history.jsonl"),
    JSON.stringify(historyEntry) + "\n"
  );

  const d = new Date(result.timestamp);
  const email = `Subject: Research Scout Daily Digest — ${d.toLocaleDateString("en-US", { month: "short", day: "2-digit", year: "numeric" })}
To: mahmoudabdelkreambusiness@gmail.com
From: Research Scout <scout@agent.local>
Date: ${d.toUTCString()}

${result.digest}

───
This digest was generated by the Research Scout agent.
Audit log: agent_mvp/audit_log.json
Run timestamp: ${result.timestamp}
`;
  await fs.writeFile(path.join(dir, "digest_email.txt"), email);
  await fs.writeFile(path.join(dir, "last_result.json"), JSON.stringify(result, null, 2));
}

export async function loadHistory(): Promise<HistoryEntry[]> {
  try {
    const raw = await fs.readFile(path.join(scoutDir(), "history.jsonl"), "utf8");
    return raw
      .split("\n")
      .map((l) => l.trim())
      .filter(Boolean)
      .map((l) => JSON.parse(l) as HistoryEntry);
  } catch {
    return [];
  }
}

export async function seenUrls(): Promise<Set<string>> {
  const history = await loadHistory();
  const urls = new Set<string>();
  for (const e of history) {
    for (const r of e.qualified_roles || []) {
      if (r.url) urls.add(r.url);
    }
  }
  return urls;
}

export async function loadLastAudit(): Promise<{
  run_timestamp: string;
  candidates_fetched: number;
  candidates_read: number;
  candidates_qualified: number;
  threshold: number;
  entries: AuditEntry[];
} | null> {
  try {
    const raw = await fs.readFile(dirFile("audit_log.json"), "utf8");
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

function dirFile(name: string) {
  return path.join(scoutDir(), name);
}

export async function loadLastResult(): Promise<ScoutRunResult | null> {
  try {
    const raw = await fs.readFile(dirFile("last_result.json"), "utf8");
    return JSON.parse(raw) as ScoutRunResult;
  } catch {
    return null;
  }
}

export async function loadLastDigest(): Promise<string> {
  try {
    return await fs.readFile(dirFile("digest_email.txt"), "utf8");
  } catch {
    return "";
  }
}

export function weeklySummary(entries: HistoryEntry[], days = 7) {
  const cutoff = Date.now() - days * 24 * 60 * 60 * 1000;
  const window = entries.filter((e) => {
    const t = Date.parse(e.timestamp);
    return Number.isFinite(t) ? t >= cutoff : true;
  });
  if (!window.length) return "No runs in the specified period.";

  const totalFetched = window.reduce((s, e) => s + (e.candidates_fetched || 0), 0);
  const totalRead = window.reduce((s, e) => s + (e.candidates_read || 0), 0);
  const totalQualified = window.reduce((s, e) => s + (e.candidates_qualified || 0), 0);
  const allRoles = window.flatMap((e) => e.qualified_roles || []);
  const uniqueUrls = new Set(allRoles.map((r) => r.url));

  const lines: string[] = [];
  lines.push("RESEARCH SCOUT — WEEKLY SUMMARY");
  lines.push(`${window[0].date} → ${window[window.length - 1].date}`);
  lines.push(`Total runs: ${window.length}`);
  lines.push("");
  lines.push("── AGGREGATE STATS ──");
  lines.push(`  Fetched: ${totalFetched}  Read: ${totalRead}  Qualified: ${totalQualified}`);
  lines.push(`  Unique qualified roles: ${uniqueUrls.size}`);
  lines.push("");
  lines.push("── PER-DAY BREAKDOWN ──");
  for (const e of window) {
    lines.push(
      `  ${e.date}  fetched ${e.candidates_fetched}  read ${e.candidates_read}  qualified ${e.candidates_qualified}`
    );
  }
  lines.push("");
  lines.push("── TOP ROLES ──");
  [...allRoles]
    .sort((a, b) => (b.score || 0) - (a.score || 0))
    .filter((r, i, arr) => arr.findIndex((x) => x.url === r.url) === i)
    .slice(0, 10)
    .forEach((r, i) => {
      lines.push(`  [${i + 1}] ${r.score}/9 — ${r.title}`);
      lines.push(`       ${r.source} · ${r.url}`);
    });

  const sources: Record<string, number> = {};
  for (const r of allRoles) sources[r.source] = (sources[r.source] || 0) + 1;
  lines.push("");
  lines.push("── SOURCE DISTRIBUTION ──");
  Object.entries(sources)
    .sort((a, b) => b[1] - a[1])
    .forEach(([s, n]) => lines.push(`  ${s}: ${n}`));

  lines.push("");
  lines.push("── GOAL CHECK ──");
  lines.push(`  Target: 2-3 applications/week`);
  lines.push(`  Unique qualified roles this period: ${uniqueUrls.size}`);
  if (uniqueUrls.size >= 2) lines.push("  Enough qualified roles to hit target (you still apply).");
  else if (uniqueUrls.size >= 1) lines.push("  Below target — thin week.");
  else lines.push("  No qualified roles this period.");

  return lines.join("\n");
}

export { SCORE_THRESHOLD };
